# Generated by Django 4.1.13 on 2024-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_watchlist_remove_user_watchlists_user_watchlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlists',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlists',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
